### ISSUE TITLE
Generated selectors specificity isn't the same as the written selectors

### ISSUE THREAD

**Issue by ahmadalfy** [BuilderIO/qwik#1771]
Greetings,

I generated a new Qwik project using `npm create qwik@latest` and used the first option then I tried to make some edits to the header component. I added a class to one of the menu items to make it highlighted. Now this is the original CSS that's written in the component files:

```css
header li a {
  display: inline-block;
  padding: 15px 10px;
  text-decoration: none;
}
```

I added the following class

```css
.highlighted {
  padding-inline: 30px;
}
```

The generated CSS is like the following:

```css
header.⭐️rwl3jt-0 li.⭐️rwl3jt-0 a.⭐️rwl3jt-0 {
    display: inline-block;
    padding: 15px 10px;
    text-decoration: none;
}

.highlighted.⭐️rwl3jt-0 {
  padding-inline: 30px;
}
```

According to the pre-compiled style, the anchor with the `highlighted` class should have its inline padding value set to 30px because the specificity of `.highlighted` selector is bigger than `header li a` selector. The compiled styles gives a higher specificity to the second selector which is wrong.

I didn't use styled components or CSS Modules before in other frameworks so I am not sure if people are familiar with issues like these (except maybe scoped styles in Angular which doesn't show that behavior).
