### ISSUE TITLE
Scope styling anchor elements rendered from <Link>

### ISSUE THREAD

**Issue by angelovdev** [BuilderIO/qwik#2071]
### Qwik Version

0.12.1 / 0.0.118

### Operating System (or Browser)

Linux

### Node Version (if applicable)

19

### Which component is affected?

Qwik City

### Expected Behaviour

```tsx
<Link href="/">
    <img src="/icon.svg" /> 
</Link>
```
inside a component that uses `useStylesScoped$` with this CSS

```css
a {
  display: flex;
}
```

renders this scoped CSS:

```css
a.⭐️rwl3jt-0 {
  display: flex;
}
```

Anchor tags should have a scoped class applied and the anchor element should get a `display: flex;`

```html
<a href="/" preventdefault:click="" on:click="..." on:mouseover="..." on:qvisible="..." q:id="9" class="⭐️rwl3jt-0">
  <!--qv q:s q:sref=8 q:key=-->
    <img src="/icon.svg" class="⭐️rwl3jt-0">
  <!--/qv-->
</a>
```

### Actual Behaviour

```tsx
<Link href="/">
    <img src="/icon.svg" /> 
</Link>
```
inside a component that uses `useStylesScoped$` with this CSS

```css
a {
  display: flex;
}
```

renders this scoped CSS:

```css
a.⭐️rwl3jt-0 {
  display: flex;
}
```

There is no class applied to the anchor rendered from the Link component and the anchor does not get the styles:

```html
<a href="/" preventdefault:click="" on:click="..." on:mouseover="..." on:qvisible="..." q:id="9">
  <!--qv q:s q:sref=8 q:key=-->
    <img src="/icon.svg" class="⭐️rwl3jt-0">
  <!--/qv-->
</a>
```

### Additional Information

Other scoped styles work so I assume everything is correctly imported on my side.
